version: '3'
services:
  fastapi:
    build: ./fastapi
    ports:
      - "8000:8000"

  ml-service:
    build: ./machine_learning
    ports:
      - "5000:5000"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.4
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.4
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
