version: '3'

services:
  fastapi:
    build: ./fastapi1
    ports:
      - "8000:8000"
    networks:
      - elastic

  elasticsearch:
    image: elasticsearch:8.10.4
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - elastic

  kibana:
    image: kibana:8.10.4
    environment:
      - "ELASTICSEARCH_HOSTS=http://elasticsearch:9200"
    ports:
      - "5601:5601"
    networks:
      - elastic
    depends_on:
      - elasticsearch

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - elastic

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    networks:
      - elastic

ml-service:
    build: ./chemin_vers_le_dossier_ml
    ports:
      - "5000:5000"
    networks:
      - elastic
  
networks:
  elastic:
    driver: bridge
