global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'fastapi'
    metrics_path: /metrics
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_namespace]
        action: keep
        regex: (default|dev|prod|test) # Surveillez les namespaces default, dev, prod et test
      - source_labels: [__address__]
        action: replace
        regex: ([^:]+)(:80)(;)?
        replacement: $1:8000 # Utilisez le port 8000 pour le scrap des métriques
      - source_labels: [__meta_kubernetes_pod_label_app]
        action: keep
        regex: fastapi # Surveillez les pods avec l'étiquette 'app' ayant la valeur 'fastapi'
