global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'kubernetes-pods'
    scrape_interval: 15s
    metrics_path: /metrics
    scheme: http
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
            - test
            - dev
            - prod
    relabel_configs:
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: namespace
      - source_labels: [__meta_kubernetes_pod_label_app]
        action: replace
        target_label: app

  - job_name: 'mysql'
    static_configs:
      - targets: ['mysqld-exporter:9104']

      # Vous pouvez ajouter plus de relabel_configs ici si nécessaire.
