apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      serviceAccountName: prometheus-sa  # Déplacer ici pour appliquer au Pod entier
      containers:
      - name: prometheus
        image: prom/prometheus:latest
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus  # Monter tout le répertoire pour accéder à tout le contenu du ConfigMap
      volumes:
      - name: config-volume
        configMap:
          name: prometheus-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |  # C'est la configuration de Prometheus, assurez-vous qu'elle correspond bien à vos besoins
    global:
      scrape_interval: 15s

    scrape_configs:
    - job_name: 'kubernetes-pods'
      scrape_interval: 15s
      metrics_path: /metrics
      scheme: http
      kubernetes_sd_configs:
      - role: pod
