global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'kubernetes-pods'
    scrape_interval: 15s
    metrics_path: /metrics
    scheme: http
    kubernetes_sd_configs:
      - role: pod
      namespaces:
        names:
          - test
          - dev
          - prod
