pipeline {
    agent any

    stages {
        stage('Build Docker Image') {
            steps {
                script {
                    // Définir les variables
                    def DOCKER_ID = "mlops_2023"
                    def DOCKER_IMAGE = "weather_forecast-fastapi"
                    def DOCKER_TAG = "${BUILD_ID}.0"

                    // Étape de construction de l'image Docker
                    sh "docker build -t ${DOCKER_ID}/${DOCKER_IMAGE}:${DOCKER_TAG} ."
                }
            }
        }

        stage('Run Docker Container') {
            steps {
                script {
                    // Étape d'exécution du conteneur Docker
                    sh "docker run -d -p 80:80 --name mon-container ${DOCKER_ID}/${DOCKER_IMAGE}:${DOCKER_TAG}"
                }
            }
        }

        stage('Test FastAPI') {
            steps {
                script {
                    // Étape de test FastAPI (personnalisez ici pour vos tests)
                    sh "curl http://localhost"
                }
            }
        }
    }
}
