pipeline {
    environment {
        DOCKER_ID = "mlops_weather" // Remplacez par votre ID Docker
        DOCKER_IMAGE = "fastapi-app" // Nom de l'image pour le service FastAPI
        DOCKER_TAG = "v.${BUILD_ID}.0" // Tag basé sur l'ID de build
    }
    agent any
    stages {
        stage('Docker Build') {
            steps {
                script {
                    sh '''
                    docker rm -f fastapi-container || true
                    docker build -t $DOCKER_ID/$DOCKER_IMAGE:$DOCKER_TAG .
                    sleep 6
                    '''
                }
            }
        }
        stage('Docker Run') {
            steps {
                script {
                    sh '''
                    docker run -d -p 8000:8000 --name fastapi-container $DOCKER_ID/$DOCKER_IMAGE:$DOCKER_TAG
                    sleep 10
                    '''
                }
            }
        }
        stage('Test Acceptance') {
            steps {
                script {
                    sh 'curl localhost'
                }
            }
        }
        stage('Docker Push') {
            environment {
                DOCKER_PASS = credentials("DOCKER_HUB_PASS")
            }
            steps {
                script {
                    sh '''
                    docker login -u $DOCKER_ID -p $DOCKER_PASS
                    docker push $DOCKER_ID/$DOCKER_IMAGE:$DOCKER_TAG
                    '''
                }
            }
        }
        // Ajoutez les étapes de déploiement similaires à celles que vous avez mentionnées
        // ...
    }
    post {
        failure {
            mail to: "b2o936@gmail.com",
                 subject: "Echec du build FastAPI: ${env.JOB_NAME} #${env.BUILD_ID}",
                 body: "Consulter les détails du build: ${env.BUILD_URL}"
        }
    }
}

