version: '3.8'
services:
  app:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ~/mlops_weather_data:/app/data
      - ~/mlops_weather_monitoring:/app/monitoring

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ~/mlops_weather_monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - app

volumes:
  grafana_data:
    driver: local
