version: '3.8'
services:
  app:
    build:
      context: ../
      dockerfile: deployment/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - /var/lib/jenkins/workspace/mlops_weather/data:/data  # Montage du volume vers un autre répertoire dans le conteneur  

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.15
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: kibana:7.17.15
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ../monitoring/prometheus.yml:/etc/prometheus/prometheus.yml  # Chemin du fichier de configuration Prometheus
    depends_on:
      - app

volumes:
  esdata:
    driver: local
