version: '3.8'
services:
  app:
    build:
      context: .  # Le contexte de construction est le répertoire actuel
      dockerfile: Dockerfile  # Utilisation du Dockerfile dans le répertoire courant
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data  # Monter le dossier data local

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.15
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: kibana:7.17.15
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - app

volumes:
  esdata:
    driver: local
