apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      initContainers:
      - name: init-db
        image: mlopsweather2023/mysql-image:latest
        volumeMounts:
        - name: init-script
          mountPath: /docker-entrypoint-initdb.d
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "mysecretpassword"
      containers:
      - name: mysql
        image: mlopsweather2023/mysql-image:latest
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: init-script
          mountPath: /docker-entrypoint-initdb.d
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "mysecretpassword"
      volumes:
      - name: init-script
        configMap:
          name: mysql-init-script

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-script
data:
  init.sql: |
    -- Vérifiez si la base de données existe, sinon créez-la
    CREATE DATABASE IF NOT EXISTS mlops_weather;
    USE mlops_weather;

    -- Créez la table weather_predictions si elle n'existe pas
    CREATE TABLE IF NOT EXISTS weather_predictions (
        id INT PRIMARY KEY,
        date DATE,
        location VARCHAR(255),
        prediction INT,
        accuracy FLOAT
    );
