apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-exporter
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-exporter
  template:
    metadata:
      labels:
        app: mysql-exporter
    spec:
      containers:
      - name: mysql-exporter
        image: prom/mysqld-exporter
        env:
        - name: DATA_SOURCE_NAME
          value: user:password@(mysql-service.test.svc.cluster.local:3306)/dbname
        ports:
        - containerPort: 9104
