pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/TeamMlops2023/Weather_Forecast.git'
            }
        }

        stage('Build and Deploy') {
            steps {
                script {
                    dir('Weather_Forecast') {
                        sh 'docker-compose up -d'
                    }
                }
            }
        }

        // Ajoutez d'autres étapes au besoin
    }
}
