pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                // Assurez-vous de spécifier la branche que vous souhaitez extraire
                git branch: 'BAS_ALAIN', url: 'https://github.com/TeamMlops2023/Weather_Forecast.git'
            }
        }

        stage('Build and Deploy') {
            steps {
                script {
                    // Utiliser le chemin relatif vers le fichier docker-compose.yml
                    sh 'docker-compose -f docker-compose.yml up -d'
                }
            }
        }

        // Ajoutez d'autres étapes au besoin
    }

    post {
        always {
            script {
                // Nettoyer les services Docker Compose après le build
                sh 'docker-compose -f docker-compose.yml down'
            }
        }
    }
}
