pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                // Cloner le dépôt Git
                git 'https://github.com/TeamMlops2023/Weather_Forecast.git'
            }
        }

        stage('Build and Deploy') {
            steps {
                script {
                    // Naviguer au répertoire contenant le docker-compose.yml
                    dir('Weather_Forecast') {
                        // Lancer docker-compose
                        sh 'docker-compose up -d'
                    }
                }
            }
        }

        // Vous pouvez ajouter des étapes supplémentaires si nécessaire
    }

    post {
        always {
            // Actions de nettoyage ou autres étapes post-build
        }
    }
}
