version: '3'
services:
  webserver:
    image: apache/airflow:2.8.1
    command: >
      bash -c "airflow db upgrade && airflow users create --username admin --firstname FIRSTNAME --lastname LASTNAME --role Admin --email admin@example.com --password admin && airflow webserver"
    ports:
      - "8090:8080"
    volumes:
      - ./dags:/opt/airflow/dags
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
    restart: always

  scheduler:
    image: apache/airflow:2.8.1
    command: scheduler
    volumes:
      - ./dags:/opt/airflow/dags
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
    restart: always
