version: '3'
services:
  webserver:
    image: apache/airflow:2.8.1
    command: >
      bash -c "airflow db upgrade && airflow webserver"
    ports:
      - "8090:8080"
    volumes:
      - ./dags:/opt/airflow/dags
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
    restart: always
