apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-model-deployment
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-model
  template:
    metadata:
      labels:
        app: ml-model
    spec:
      containers:
        - name: ml-model
          image: mlopsweather2023/ml-model-image:latest
          ports:
            - containerPort: 8000
          env:
            - name: ML_ENVIRONMENT
              value: "test"
            - name: MYSQL_HOST
              value: "database-service.test"
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_PASSWORD
              value: "mysecretpassword"
            - name: MYSQL_DATABASE
              value: "mlops_weather"
