apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-model-deployment
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-model
  template:
    metadata:
      labels:
        app: ml-model
    spec:
      containers:
        - name: ml-model
          image: mlopsweather2023/ml-model-image:latest
          env:
            - name: ML_ENVIRONMENT
              value: "prod"
            - name: MYSQL_HOST
              value: "database-service.prod"
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_PASSWORD
              value: "mysecretpassword"
            - name: MYSQL_DATABASE
              value: "mlops_weather"
