# Configuration du déploiement FastAPI
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment # Nom du déploiement
spec:
  replicas: 1 # Nombre de pods à déployer
  selector:
    matchLabels:
      app: fastapi # Sélectionne les pods avec l'étiquette 'app' ayant la valeur 'fastapi'
  template:
    metadata:
      labels:
        app: fastapi # Applique l'étiquette 'app' avec la valeur 'fastapi' aux pods créés
    spec:
      containers:
      - name: fastapi-container # Nom du conteneur
        image: mlopsweather2023/fastapi-image:latest # Image Docker à utiliser pour ce conteneur
        ports:
        - containerPort: 8000 # Port sur lequel le conteneur écoute
        
        # Commentaires :
        # Le code ci-dessus définit un déploiement Kubernetes qui déploie un seul pod FastAPI.
        # - 'replicas' spécifie le nombre de répliques (pods) à créer, dans ce cas, 1.
        # - 'selector' spécifie les pods à sélectionner en fonction de leurs étiquettes (labels).
        # - 'template' spécifie le modèle de pod à créer.
        # - Dans le modèle de pod, nous définissons un seul conteneur Docker (fastapi-container)
        #   basé sur l'image Docker 'mlopsweather2023/fastapi-image:latest' et écoutant le port 8000.
        # - L'étiquette 'app' avec la valeur 'fastapi' est appliquée au pod et au conteneur.
        #   Cela permet au service et à d'autres composants de Kubernetes de cibler ce pod en fonction de son étiquette.
