# config de deploiement
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi-container
        image: mlopsweather2023/fastapi-image:latest
        ports:
        - containerPort: 8000
      - name: port-forward-container
        image: kubectl
        command: ["kubectl"]
        args: ["port-forward", "fastapi-deployment-65c57fd9f6-kbdw2", "8081:8000"]
