apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqld-exporter
  labels:
    app: mysqld-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysqld-exporter
  template:
    metadata:
      labels:
        app: mysqld-exporter
    spec:
      containers:
      - name: mysqld-exporter
        image: prom/mysqld-exporter:latest  # Remplacez 'latest' par une version spécifique si nécessaire
        env:
        - name: DATA_SOURCE_NAME
          value: "mlops:mlops@(10.96.39.152:3306)/mlops_weather"  # Assurez-vous que 'mlops' est le mot de passe correct
        ports:
        - containerPort: 9104
